# Render deployment configuration

services:
  # Main web service
  - type: web
    name: dear-teddy
    env: python
    plan: starter
    buildCommand: ./build.sh
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers=2 --threads=4 --timeout=120 main:app
    healthCheckPath: /r-login
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: RENDER
        value: true
      - key: DATABASE_URL
        sync: false
      - key: SESSION_SECRET
        generateValue: true
      - key: OPENAI_API_KEY
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false