services:
  - type: web
    name: dear-teddy
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn wsgi:application --bind 0.0.0.0:$PORT --workers 1 --timeout 120 --log-level info
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: SESSION_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: dear-teddy-db
          property: connectionString
    healthCheckPath: /health

databases:
  - name: dear-teddy-db
    databaseName: dear_teddy
    user: dear_teddy_user