services:
  - type: web
    name: dear-teddy
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --bind 0.0.0.0:$PORT --reuse-port --reload render_app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.10
      - key: DATABASE_URL
        fromDatabase:
          name: dear-teddy-db
          property: connectionString

  - type: cron
    name: nightly-backup
    env: python
    schedule: "0 2 * * *"  # 02:00 UTC daily
    buildCommand: "pip install -r requirements.txt"
    startCommand: "bash scripts/backup_db.sh"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dear-teddy-db
          property: connectionString
      - key: AWS_ACCESS_KEY_ID
        fromGroup: aws-credentials
      - key: AWS_SECRET_ACCESS_KEY
        fromGroup: aws-credentials

databases:
  - name: dear-teddy-db
    databaseName: dearteddy
    user: dearteddy