from flask import Flask, render_template_string
import sys
import os

# Basic Flask app for testing
app = Flask(__name__)

# Sample journal entry that we want to analyze
SAMPLE_ENTRY = {
    "content": "my partner went away for 10 day. for teh first 2 days she messaged briefly, the finallly she called on the 3rd day. i missed her call but wheni called back she was at home with family and was talking to me, but most of the time i spent listening to her talking to others. her mum then called and she told me she woudl call me back, but she didnt. following day she messaged good mornng and said she was out and about at work. nothing since. how shoudl i feel",
    "anxiety_level": 6,
    "title": "Relationship Issues"
}

# HTML template to display results
TEST_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <title>Test Mira's Enhanced Response</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            line-height: 1.6;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
        }
        h1 {
            color: #4a6da7;
        }
        .journal-entry {
            background-color: #f5f5f5;
            padding: 15px;
            border-radius: 5px;
            margin-bottom: 20px;
        }
        .response {
            background-color: #e8f4ff;
            padding: 15px;
            border-radius: 5px;
            white-space: pre-wrap;
        }
        .section {
            margin-bottom: 30px;
        }
        h2 {
            color: #5a5a5a;
            margin-bottom: 10px;
        }
    </style>
</head>
<body>
    <h1>Test Mira's Enhanced CBT Response</h1>
    
    <div class="section">
        <h2>Journal Entry</h2>
        <div class="journal-entry">
            <p><strong>Title:</strong> {{ entry.title }}</p>
            <p><strong>Anxiety Level:</strong> {{ entry.anxiety_level }}/10</p>
            <p><strong>Content:</strong></p>
            <p>{{ entry.content }}</p>
        </div>
    </div>
    
    <div class="section">
        <h2>Mira's Enhanced Response</h2>
        <div class="response">
            {{ response }}
        </div>
    </div>
</body>
</html>
"""

@app.route('/')
def test_mira_response():
    """
    Test page to show Mira's enhanced response to the sample journal entry.
    """
    # This would be where we call our enhanced response generator
    # For now, just display what would happen in the real app
    response = """
NOTE: This is where Mira's enhanced response would appear.

In the actual application, we would call:
```python
from openai_service import generate_journaling_coach_response

class MockEntry:
    def __init__(self):
        self.content = "...sample content..."
        self.anxiety_level = 6
        self.title = "Relationship Issues"

enhanced_response = generate_journaling_coach_response(MockEntry())
```

The OpenAI service would then generate a CBT-based response using the enhanced prompt that:
1. Validates specific emotions (e.g., "neglected," "anxious," "unimportant")
2. Detects and labels thought patterns with depth, connecting to emotional needs
3. Explores relationship context with clarifying questions 
4. Offers practical action steps including scripted "I-statements"
5. Encourages self-reflection with identifying core emotional needs
6. Balances support and challenge, encouraging courageous action
7. Closes warmly

To see the actual enhanced response in the real application, you would need to:
1. Create a journal entry in the app
2. View the response generated by the enhanced prompt
"""
    
    return render_template_string(TEST_TEMPLATE, entry=SAMPLE_ENTRY, response=response)

if __name__ == '__main__':
    port = int(os.environ.get('PORT', 8080))
    app.run(host='0.0.0.0', port=port, debug=True)